name: "Initiate Approval with Logic App"
description: "Runs Azure Logic app for approvals"
author: "test"
inputs:
  url:
    description: Callback Url for Azure Logic App
    required: true
  approvers:
    description: List of approvers
    required: true
  repo-token:
    description: Repository token to make a callback event on completion of approval
    required: true
  instructions:
    description: HTTP request payload
outputs:
  status:
    description: The status of the HTTP request
  headers:
    description: The response HTTP headers
  response:
    description: The raw query response body
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'aperture'
  color: 'green'
